#! /bin/sh

# Runs a program unless that program is already running
function conditional_run {
  local program_name=$1

  ps_result=$(ps aux \
      | grep "${program_name}" \
      | grep -v "grep" \
      | wc -l
      )
  if [ $ps_result -eq 0 ]; then
      echo "Running $program_name"
      `$program_name` &
  else
      echo "$program_name already running"
  fi
}

bspc rule -a smplayer state=floating sticky=on

killall /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
killall btops; btops &
killall picom; picom --config ~/.config/picom.conf -b --experimental-backends &
killall fcitx; fcitx -dr &
# killall telegram-desktop; telegram-desktop &
# killall x0vncserver; x0vncserver -display :0 -passwordfile ~/.vnc/passwd &
# killall xss-lock; xss-lock -- ~/.config/bspwm/lock.sh &
$HOME/.config/polybar/launch.sh
wmname LG3D

conditional_run SVPManager
conditional_run transgui
conditional_run nm-applet
conditional_run blueman-applet
conditional_run pasystray
conditional_run sxhkd
conditional_run mpd
conditional_run dunst
conditional_run thunderbird
conditional_run /usr/lib/gsd-xsettings
conditional_run slack
# mpc -h localhost add https://music.alien.moe
# mpc -h localhost stop
libinput-gestures-setup restart

gnome-keyring-daemon --start --components=pkcs11 &

# Wallpaper
# feh --bg-fill ~/.config/wallpaper/wallpaper2.jpeg &
nitrogen --restore &

# Elan input setting
xinput set-prop 'Elan Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop 'Elan Touchpad' 'libinput Natural Scrolling Enabled' 1
# magic trackpad 2
xinput set-prop 'Apple Inc. Magic Trackpad 2' 'libinput Accel Speed' 0.3
xinput set-prop 'Apple Inc. Magic Trackpad 2' 'libinput Natural Scrolling Enabled' 1
# Logitech G402
xinput set-prop 'Logitech Gaming Mouse G402' 'libinput Accel Speed' -0.8

# Default Cursor
xsetroot -cursor_name left_ptr

bspc rule -a '*:zathura' state=tiled
bspc rule -a Teamviewer state=floating
bspc rule -a Transgui state=floating

bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          25

bspc config normal_border_color "#000000"
bspc config focused_border_color "#dd5555"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

